#!/usr/bin/lua

local filename = select(1, ...)

-- Disable stack traces, keep error messages small
debug.traceback = nil

-- Fail early if no filename was given
if not filename then
    io.stderr:write "No file was specified\nUsage: mdview FILE\n"
    os.exit(1)
end

-- Try to read file before loading GTK
local file = assert(io.open(filename, "r"))
local text = file:read("*a")
file:close()

local lunamark = require "lunamark"
local lgi = require "lgi"
local markdown = lunamark.reader.markdown.new(lunamark.writer.html5.new())
local Gtk, Gio, Gdk, WebKit = lgi.Gtk, lgi.Gio, lgi.Gdk, lgi.WebKit
local app = Gtk.Application.new("org.mdview", Gio.ApplicationFlags.HANDLES_OPEN)
local urichanged = false

local html = ([[
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Markdown Preview</title>
    <style>
        body {
            margin: 15px;
            font: 14px/1.6 Helvetica, arial, freesans, clean, sans-serif;
            color: #333;
        }
        a {
            color: #4183C4;
            text-decoration: none;
        }
        a:hover {
            color: #ff6600;
            text-decoration: none;
        }
        h1, h2, h3, h4, h5, h6 {
            margin: 20px 0 10px;
            padding: 0;
            font-weight: bold;
        }
        h2 {
            font-size: 24px;
            line-height: 1.6;
            border-bottom: 1px solid #CCC;
        }
        pre, code, tt {
            font: normal 12px/19px Consolas, Courier, monospace;
        }
        pre {
            background-color: #F8F8F8;
            border: 1px solid #CCC;
            overflow: auto;
            padding: 6px 10px;
            border-radius: 3px;
        }
    </style>
</head>
<body>
    %s
</body>
</html>
]]):format(markdown(text))

app.on_activate = function()
    local webview = WebKit.WebView.new()

    local window = Gtk.Window {
        type = Gtk.WindowType.TOPLEVEL,
        title = filename,
        application = app,
        hide_titlebar_when_maximized = true,
        default_width = 580,
        default_height = 500,
        Gtk.ScrolledWindow {
            expand = true,
            webview
        },
        on_show = function()
            webview:load_html_string(html, os.getenv("PWD"))
        end,
        on_key_press_event = function(widget, event)
            if Gdk.keyval_name(event.keyval) == "BackSpace" then
                webview:load_html_string(html, os.getenv("PWD"))
                widget.title = filename
                urichanged = false
                return true
            end
        end
    }

    webview.on_notify["load-status"] = function(self, pspec)
        if not urichanged and self.uri and self.uri ~= os.getenv("PWD") then
            urichanged = true
            window.title = "Hit Backspace to return to " .. filename
        end
    end

    window:show_all()
end

return app:run()
