#!/bin/sh
# This script monitors a given directory via inotify and continuously
# opens the most recently edited Markdown document in Showdown.

set -e

abort() {
    echo "Error: $1" >&2
    exit 1
}

for command in inotifywait xdg-mime showdown; do
    if test -z "$(which $command 2>/dev/null)"; then
        abort "'$command' is required but could not be found"
    fi
done

test -n "$1" || abort "argument missing"
test -d "$1" || abort "'$1' is not a directory"

inotifywait -m -r -e create,modify,moved_to --format '%w%f' "$1" |
while read filename; do
    if test -f "$filename"; then
        m=$(xdg-mime query filetype "$filename" 2>/dev/null || :)
        if test "$m" = "text/markdown" -o "$m" = "text/x-markdown"; then
            showdown -w "$filename" &
        fi
    fi
done
